// <auto-generated />
namespace InfraestruraPokemon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PokeMigracion2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PokeMigracion2));
        
        string IMigrationMetadata.Id
        {
            get { return "202204041420022_PokeMigracion2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
